### ISSUE TITLE
Shown Datas are not correct ...

### ISSUE THREAD

**Issue by 85siva** [scoutapp/scout_realtime#13]
We have installed then checked cpu and mysqld which usage is much mismatched 

Refer the attachment -

![screen shot 2014-03-11 at 5 04 39 pm](https://f.cloud.github.com/assets/1804288/2384680/28f6b798-a911-11e3-8977-1baf57566f98.png)

Using Top command 

![screen shot 2014-03-11 at 5 05 10 pm](https://f.cloud.github.com/assets/1804288/2384681/313d0286-a911-11e3-95cc-324d2f54bce7.png)

Let me know in case anything we missed ...

**Comment by itsderek23** [comment]
Hi @85siva,

scout_realtime displays cpu usage as a percentage of the total cpus on the server. Top displays cpu usage as if it was a 1-core system. Since you have 24 cores, 98% cpu usage in scout_realtime would be 98/24=4% which is within range of what we'd expect.

Also, I don't see any charts in your screenshot. Are those missing for you? If so, mind sharing your:
- operating system
- browser
- browser version

**Comment by itsderek23** [comment]
Going to close this for now. Re-open if you are able to collect the details behind the chart issues.
